pipeline {
    agent any
    stages{
        stage("Clone Code"){
            steps{
                git url: "https://github.com/Abhishek-2502/Docker_K8s.git", branch: "main"
            }
        }
        stage("Build and Test"){
            steps{
                dir("K8s/Basics/Ingress/Project/django-notes-app") {
                    sh "docker build . -t note-app-test-new"
                }
            }
        }
        stage("Push to Docker Hub"){
            steps{
                dir("K8s/Basics/Ingress/Project/django-notes-app") {
                    withCredentials([usernamePassword(credentialsId:"dockerHub",passwordVariable:"dockerHubPass",usernameVariable:"dockerHubUser")]){
                        sh "docker tag note-app-test-new ${env.dockerHubUser}/note-app-test-new:latest"
                        sh "docker login -u ${env.dockerHubUser} -p ${env.dockerHubPass}"
                        sh "docker push ${env.dockerHubUser}/note-app-test-new:latest"
                    }
                }
            }
        }
        stage("Deploy"){
            steps{
                dir("K8s/Basics/Ingress/Project/django-notes-app") {
                    sh "docker-compose down && docker-compose up -d"
                }
            }
        }
    }
}
