kind: Pod
apiVersion: v1
metadata:
  name: nginx-pod-toleration
  namespace: taints-demo
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80

  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "backend"
      effect: "NoSchedule"