apiVersion: v1
kind: Service
metadata:
  name: nginx-probes-service
  namespace: probe-demo
spec:
  selector:
    app: nginx-probes
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
